
------------------------------------------- WHERE PROJECT OFFUTURE ANALYTICS -------------------------------------------


-- Lawrence Hide
-- Abhishek Ladwa
-- Momin Mirza


------------------------------------------------------ OVERVIEW --------------------------------------------------------


-- SECTION ONE - GENERAL BUSINESS HEALTH --
-- SECTION TWO - PRODUCT AND CATEGORY INSIGHTS --
-- SECTION THREE - MARKET INSIGHTS --


---------------------------------------------------- SECTION ONE -------------------------------------------------------

                                            -- GENERAL BUSINESS HEALTH --

-- Below is the SQL query that was exported to Tableau for graph creation --

SELECT
    row_id,
    order_id,
    order_date,
    market,
    region,
    country,
    category,
    sub_category,
    sales,
    profit
FROM
    student.where_project_offuture;

-- Row ID in case we needed to identify different transactions/to make sure different transactions were not lost
-- Order ID to identify different orders
-- Order Date to provide a timestamp/timescale for investigation
-- Market in order to identify geographical trends
-- Region in order to zoom geographically
-- Country in order to zoom geographically
-- Category to understand sales and profit across profit categories
-- Sub-categories to seek insight across sub-categories
-- Sales to total up sales figures across other variables
-- Profit to total up profit across other variables

-- FROM THIS QUERY WE GENERATED THE FOLLOWING IN TABLEAU --

-- SMA Sales
-- SMA Profit
-- Seasonal Picture Quarter to Quarter
-- Profit Growth Statistics --> Sales and Profit increasing but growth slowing
-- Graphs showing market performance


-- Table generated by the query below shows the total sales, profit and profit margin --

SELECT year, sales, profit, ((profit/sales) * 100) as profit_margin
FROM (
         SELECT SUM(sales) AS sales, SUM(profit) as profit, '2011' AS year
         FROM student.where_project_offuture
         WHERE order_date LIKE '%2011%'

         UNION ALL

         SELECT SUM(sales) AS sales, SUM(profit) as profit, '2012' AS year
         FROM student.where_project_offuture
         WHERE order_date LIKE '%2012%'

         UNION ALL

         SELECT SUM(sales) AS sales, SUM(profit) as profit, '2013' AS year
         FROM student.where_project_offuture
         WHERE order_date LIKE '%2013%'

         UNION ALL

         SELECT SUM(sales) AS sales, SUM(profit) as profit, '2014' AS year
         FROM student.where_project_offuture
         WHERE order_date LIKE '%2014%'
     ) AS sub_query
ORDER BY sales DESC;




---------------------------------------------------- SECTION TWO -------------------------------------------------------

                                         -- PRODUCT AND CATEGORY INSIGHTS --

-- Most Profitable Category --

SELECT
    category, SUM(profit) as max_profit
FROM
    student.where_project_offuture
GROUP BY
    category
ORDER BY
    max_profit DESC;

-- Profit Per Category Per Year --
SELECT
    subcat11.category,
    sum_sales_2011,
    sum_sales_2012,
    sum_sales_2013,
    sum_sales_2014
FROM
    (SELECT
         category,
         sum(sales) as sum_sales_2011
     FROM
         student.where_project_offuture
     WHERE
             order_date like '%2011%'
     GROUP BY
         category) AS subcat11
        JOIN (SELECT
                  category,
                  sum(sales) as sum_sales_2012
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2012%'
              GROUP BY
                  category) AS subcat12 on subcat11.category = subcat12.category
        JOIN (SELECT
                  category,
                  sum(sales) as sum_sales_2013
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2013%'
              GROUP BY
                  category) AS subcat13 on subcat13.category = subcat12.category
        JOIN (SELECT
                  category,
                  sum(sales) as sum_sales_2014
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2014%'
              GROUP BY
                  category) AS subcat14 on subcat14.category = subcat13.category;

-- Category Growth Year on Year --

SELECT
    subcat11.category,
    ((sum_sales_2012-sum_sales_2011)/sum_sales_2011 * 100) as perc_change_2011_to_2012,
    ((sum_sales_2013-sum_sales_2012)/sum_sales_2012 * 100) as perc_change_2012_to_2013,
    ((sum_sales_2014-sum_sales_2013)/sum_sales_2013 * 100) as perc_change_2013_to_2014
FROM
    (SELECT
         category,
         sum(sales) as sum_sales_2011
     FROM
         student.where_project_offuture
     WHERE
             order_date like '%2011%'
     GROUP BY
         category) AS subcat11
        JOIN (SELECT
                  category,
                  sum(sales) as sum_sales_2012
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2012%'
              GROUP BY
                  category) AS subcat12 on subcat11.category = subcat12.category
        JOIN (SELECT
                  category,
                  sum(sales) as sum_sales_2013
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2013%'
              GROUP BY
                  category) AS subcat13 on subcat13.category = subcat12.category
        JOIN (SELECT
                  category,
                  sum(sales) as sum_sales_2014
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2014%'
              GROUP BY
                  category) AS subcat14 on subcat14.category = subcat13.category
ORDER BY
    perc_change_2013_to_2014 DESC;

-- Most Profitable Sub-Category --

SELECT
    sub_category, SUM(profit) as max_profit
FROM
    student.where_project_offuture
GROUP BY
    sub_category
ORDER BY
    max_profit DESC;

-- Profit Per Sub-Category Per Year --

SELECT
    subcat11.sub_category,
    sum_profit_2011,
    sum_profit_2012,
    sum_profit_2013,
    sum_profit_2014
FROM
    (SELECT
         sub_category,
         sum(profit) as sum_profit_2011
     FROM
         student.where_project_offuture
     WHERE
             order_date like '%2011%'
     GROUP BY
         sub_category) AS subcat11
        JOIN (SELECT
                  sub_category,
                  sum(profit) as sum_profit_2012
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2012%'
              GROUP BY
                  sub_category) AS subcat12 on subcat11.sub_category = subcat12.sub_category
        JOIN (SELECT
                  sub_category,
                  sum(profit) as sum_profit_2013
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2013%'
              GROUP BY
                  sub_category) AS subcat13 on subcat13.sub_category = subcat12.sub_category
        JOIN (SELECT
                  sub_category,
                  sum(profit) as sum_profit_2014
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2014%'
              GROUP BY
                  sub_category) AS subcat14 on subcat14.sub_category = subcat13.sub_category;



-- Sub-Category Growth of Sales Year on Year --

SELECT
    subcat11.sub_category,
    ((sum_sales_2012-sum_sales_2011)/sum_sales_2011 * 100) as perc_change_2011_to_2012,
    ((sum_sales_2013-sum_sales_2012)/sum_sales_2012 * 100) as perc_change_2012_to_2013,
    ((sum_sales_2014-sum_sales_2013)/sum_sales_2013 * 100) as perc_change_2013_to_2014
FROM
    (SELECT
         sub_category,
         sum(sales) as sum_sales_2011
     FROM
         student.where_project_offuture
     WHERE
             order_date like '%2011%'
     GROUP BY
         sub_category) AS subcat11
        JOIN (SELECT
                  sub_category,
                  sum(sales) as sum_sales_2012
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2012%'
              GROUP BY
                  sub_category) AS subcat12 on subcat11.sub_category = subcat12.sub_category
        JOIN (SELECT
                  sub_category,
                  sum(sales) as sum_sales_2013
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2013%'
              GROUP BY
                  sub_category) AS subcat13 on subcat13.sub_category = subcat12.sub_category
        JOIN (SELECT
                  sub_category,
                  sum(sales) as sum_sales_2014
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2014%'
              GROUP BY
                  sub_category) AS subcat14 on subcat14.sub_category = subcat13.sub_category
ORDER BY
    perc_change_2013_to_2014 DESC;

-- Sub-Category Growth of Profit Year on Year --

SELECT
    subcat11.sub_category,
    ((sum_profit_2012-sum_profit_2011)/sum_profit_2011 * 100) as perc_change_2011_to_2012,
    ((sum_profit_2013-sum_profit_2012)/sum_profit_2012 * 100) as perc_change_2012_to_2013,
    ((sum_profit_2014-sum_profit_2013)/sum_profit_2013 * 100) as perc_change_2013_to_2014
FROM
    (SELECT
         sub_category,
         sum(profit) as sum_profit_2011
     FROM
         student.where_project_offuture
     WHERE
             order_date like '%2011%'
     GROUP BY
         sub_category) AS subcat11
        JOIN (SELECT
                  sub_category,
                  sum(profit) as sum_profit_2012
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2012%'
              GROUP BY
                  sub_category) AS subcat12 on subcat11.sub_category = subcat12.sub_category
        JOIN (SELECT
                  sub_category,
                  sum(profit) as sum_profit_2013
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2013%'
              GROUP BY
                  sub_category) AS subcat13 on subcat13.sub_category = subcat12.sub_category
        JOIN (SELECT
                  sub_category,
                  sum(profit) as sum_profit_2014
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2014%'
              GROUP BY
                  sub_category) AS subcat14 on subcat14.sub_category = subcat13.sub_category
ORDER BY
    perc_change_2013_to_2014 DESC;


-- How many Table Transactions are being sold for Profit vs a Loss --

SELECT
    profit_or_loss, count(*)
FROM
    (SELECT
         CASE WHEN profit > 0 THEN 'Profit'
              WHEN profit < 0 THEN 'Loss'
              ELSE 'Zero'
             END as profit_or_loss
     FROM
         (SELECT
              product_name,
              profit
          FROM
              student.where_project_offuture
          WHERE
                  sub_category = 'Tables'
          GROUP BY
              product_name, profit) as profit) as tab
GROUP BY
    profit_or_loss;

-- Tables Making a Loss --

SELECT
    product_name, sum(profit) prof
FROM
    student.where_project_offuture
WHERE
        sub_category = 'Tables'
GROUP BY
    product_name
HAVING
        sum(profit) < 0
ORDER BY
    prof;

-- Tables Making a Loss Sum --

SELECT
    sum(prof)
FROM
    (SELECT
         sum(profit) prof
     FROM
         student.where_project_offuture
     WHERE
             sub_category = 'Tables'
     GROUP BY
         product_name
     HAVING
             sum(profit) < 0
     ORDER BY
         prof) as sub_query;

-- Profitable Tables --

SELECT
     sum(profit) prof
FROM
     student.where_project_offuture
WHERE
         sub_category = 'Tables'
GROUP BY
     product_name
HAVING
         sum(profit) > 0
ORDER BY
     prof;

-- Sum of Profitable Tables --

SELECT
    sum(prof)
FROM
    (SELECT
         sum(profit) prof
     FROM
         student.where_project_offuture
     WHERE
             sub_category = 'Tables'
     GROUP BY
         product_name
     HAVING
             sum(profit) > 0
     ORDER BY
         prof) as sub_query;


-- Top 10 Most Profitable Products --

SELECT
    product_name, SUM(profit) as max_profit
FROM
    student.where_project_offuture
GROUP BY
    product_id,
    product_name
ORDER BY
    max_profit DESC
LIMIT 10;

-- Top 10 Least Profitable Products --

SELECT
    product_name, SUM(profit) as max_profit
FROM
    student.where_project_offuture
GROUP BY
    product_id,
    product_name
ORDER BY
    max_profit
LIMIT 10;

-- Product Growth From 2013 to 2014 --

SELECT
    t1.product_id,
    t1.sum_sales_2013,
    t2.sum_sales_2014,
    CASE
        WHEN t2.sum_sales_2014 > t1.sum_sales_2013 THEN 'Growth'
        WHEN t2.sum_sales_2014 < t1.sum_sales_2013 THEN 'Decline'
        ELSE 'No Change'
        END AS growth_status
FROM
    (SELECT
         product_id,
         SUM(sales) AS sum_sales_2013
     FROM
         student.where_project_offuture
     WHERE
             order_date LIKE '%2013%'
     GROUP BY
         product_id) AS t1
        INNER JOIN
    (SELECT
         product_id,
         SUM(sales) AS sum_sales_2014
     FROM
         student.where_project_offuture
     WHERE
             order_date LIKE '%2014%'
     GROUP BY
         product_id) AS t2
    ON
            t1.product_id = t2.product_id;

-- Count of Product Growth From 2013 to 2014 --

SELECT
    growth_status,
    count(*) as count
FROM
    (SELECT
         CASE
             WHEN t2.sum_sales_2014 > t1.sum_sales_2013 THEN 'Growth'
             WHEN t2.sum_sales_2014 < t1.sum_sales_2013 THEN 'Decline'
             ELSE 'No Change'
             END AS growth_status
     FROM
         (SELECT
              product_id,
              SUM(sales) AS sum_sales_2013
          FROM
              student.where_project_offuture
          WHERE
                  order_date LIKE '%2013%'
          GROUP BY
              product_id) AS t1
             INNER JOIN
         (SELECT
              product_id,
              SUM(sales) AS sum_sales_2014
          FROM
              student.where_project_offuture
          WHERE
                  order_date LIKE '%2014%'
          GROUP BY
              product_id) AS t2
         ON
                 t1.product_id = t2.product_id) as grow
GROUP BY
    growth_status
ORDER BY
    count DESC;


--------------------------------------------------- SECTION THREE ------------------------------------------------------

                                                -- MARKET INSIGHTS --

-- Top performing market (APAC) --

SELECT
    market,
    sum(sales) as sum
FROM
    student.where_project_offuture
GROUP BY
    market
ORDER BY
    sum DESC;

-- APAC In Depth --

SELECT
    country,
    sum(sales) as sum
FROM
    student.where_project_offuture
WHERE
    market = 'APAC'
GROUP BY
    country
ORDER BY
    sum DESC;


-- Top growing market 2014 --

SELECT
    market11.market,
    ((sum_sales_2012-sum_sales_2011)/sum_sales_2011 * 100) as perc_change_2011_to_2012,
    ((sum_sales_2013-sum_sales_2012)/sum_sales_2012 * 100) as perc_change_2012_to_2013,
    ((sum_sales_2014-sum_sales_2013)/sum_sales_2013 * 100) as perc_change_2013_to_2014
FROM
    (SELECT
         market,
         sum(sales) as sum_sales_2011
     FROM
         student.where_project_offuture
     WHERE
             order_date like '%2011%'
     GROUP BY
         market) AS market11
        JOIN (SELECT
                  market,
                  sum(sales) as sum_sales_2012
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2012%'
              GROUP BY
                  market) AS market12 on market11.market = market12.market
        JOIN (SELECT
                  market,
                  sum(sales) as sum_sales_2013
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2013%'
              GROUP BY
                  market) AS market13 on market13.market = market12.market
        JOIN (SELECT
                  market,
                  sum(sales) as sum_sales_2014
              FROM
                  student.where_project_offuture
              WHERE
                      order_date like '%2014%'
              GROUP BY
                  market) AS market14 on market14.market = market13.market
ORDER BY
    perc_change_2013_to_2014 DESC;